---
- hosts: localhost
  gather_facts: false
  connection: local
  tasks:
  - name: Create a VM from a template
    vmware_guest:
      hostname: "{{ vCenterName }}"
      username: "{{ vSphereUser }}"
      password: "{{ vSpherePassword }}"
      validate_certs: no
      name: "{{ item.name }}"
      state: "{{ item.state }}"
      template: "{{ template }}"
      datacenter: "{{ datacenter }}"
      folder: "{{ folder }}"
      esxi_hostname: "{{ host }}"
      hardware:
        memory_mb: "{{ item.ram }}"
        num_cpus: "{{ item.cpu }}"
        scsi: lsilogic
      wait_for_ip_address: "{{ waitForIp }}"
    delegate_to: localhost
    register: deploy
    with_items: "{{ deployments }}"
