---
- hosts: localhost
  gather_facts: false
  connection: local
  
  vars_prompt:
  - name: "vcenter_name"
    prompt: "vCenter Hostname"
    default: "vcenter.siw.network"
    private: no
  - name: "vsphere_user"
    prompt: "vCenter Username"
    default: "administrator@vsphere.siw.network"
    private: no    
  - name: "vsphere_password"
    prompt: "vCenter Password"
    default: "secret"
    private: yes
  - name: "vm_name"
    prompt: "VM Name"
    default: "new_vm_01"
    private: no
  - name: "template_name"
    prompt: "Template name"
    default: "Template-FedoraServer28"
    private: no
  - name: "datacenter_name"
    prompt: "vSphere Datacenter Name"
    default: "siw.network"
    private: no
  - name: "folder"
    prompt: "Folder this VM should be put in (usually <datacenter name>/vm)"
    default: "siw.network/vm"
    private: no
  - name: "esxi"
    prompt: "ESXi Hostname/IP"
    default: "10.0.1.5"
    private: no
  - name: "vm_ram"
    prompt: "RAM in MB"
    default: "2048"
    private: no
  - name: "vm_cpu"
    prompt: "Number of CPUs"
    default: "2"
    private: no
  - name: "vm_host_network"
    prompt: "Network the VM should be connected to"
    default: "siw.network"
    private: no
#  - name: "vm_password"
#    prompt: "Root Password"
#    default: "secret"
#    private: yes
  - name: "vm_ip"
    prompt: "IP Address"
    default: "10.0.1.123"
    private: no
  - name: "vm_netmask"
    prompt: "Netmask"
    default: "255.255.255.0"
    private: no
  - name: "vm_gateway"
    prompt: "Gateway"
    default: "10.0.1.1"
    private: no
  - name: "vm_dns1"
    prompt: "First DNS Server"
    default: "10.0.1.1"
    private: no
  - name: "vm_dns2"
    prompt: "Second DNS Server"
    default: "1.1.1.1"
    private: no
  - name: "vm_hostname"
    prompt: "Hostname"
    default: "template"
    private: no    
  - name: "vm_domain"
    prompt: "Domain"
    default: "siw.network"
    private: no
 
  tasks:
  - name: Create a VM from a template
    vmware_guest:
      hostname: '{{ vcenter_name }}'
      username: '{{ vsphere_user }}'
      password: '{{ vsphere_password }}'
      validate_certs: no
      name: '{{ vm_name }}'
      state: poweredon
      template: '{{ template_name }}'
      datacenter: '{{ datacenter_name }}'
      folder: '{{ folder }}'
      esxi_hostname: '{{ esxi }}'
      hardware:
        memory_mb: '{{ vm_ram }}'
        num_cpus: '{{ vm_cpu }}'
        scsi: lsilogic
      networks:
      - name: '{{ vm_host_network }}'
        start_connected: true
        ip: '{{ vm_ip }}'
        netmask: '{{ vm_netmask }}'
        gateway: '{{ vm_gateway }}'
        type: static
        customization:
          autologon: yes
          dns_servers:
          - '{{ vm_dns1 }}'
          - '{{ vm_dns2 }}'
          hostname: '{{ vm_hostname }}'
          domain: '{{ vm_domain }}'
#          password: '{{ vm_password }}'
      wait_for_ip_address: yes
    delegate_to: localhost
    register: deploy
