---
- hosts: localhost
  gather_facts: false
  connection: local
  
  vars_prompt:
  - name: "vcenter_name"
    prompt: "vCenter Hostname"
    default: "vcenter.siw.network"
    private: no
  - name: "vsphere_user"
    prompt: "vCenter Username"
    default: "administrator@vsphere.siw.network"
    private: no    
  - name: "vsphere_password"
    prompt: "vCenter Password"
    default: "secret"
    private: yes
  - name: "vm_name"
    prompt: "VM Name"
    default: "new_vm_01"
    private: no
  - name: "template_name"
    prompt: "Template name"
    default: "Template-FedoraServer28"
    private: no
  - name: "datacenter_name"
    prompt: "vSphere Datacenter Name"
    default: "siw.network"
    private: no
  - name: "folder"
    prompt: "Folder this VM should be put in (usually <datacenter name>/vm)"
    default: "siw.network/vm"
    private: no
  - name: "esxi"
    prompt: "ESXi Hostname/IP"
    default: "10.0.1.5"
    private: no
  - name: "ram"
    prompt: "RAM in MB"
    default: "2048"
    private: no
  - name: "cpu"
    prompt: "Number of CPUs"
    default: "2"
    private: no
  - name: "host_network"
    prompt: "Network the VM should be connected to"
    default: "siw.network"
    private: no
 
  tasks:
  - name: Create a VM from a template
    vmware_guest:
      hostname: '{{ vcenter_name }}'
      username: '{{ vsphere_user }}'
      password: '{{ vsphere_password }}'
      validate_certs: no
      name: '{{ vm_name }}'
      state: poweredon
      template: '{{ template_name }}'
      datacenter: '{{ datacenter_name }}'
      folder: '{{ folder }}'
      esxi_hostname: '{{ esxi }}'
      hardware:
        memory_mb: '{{ ram }}'
        num_cpus: '{{ cpu }}'
        scsi: lsilogic
      networks:
      - name: '{{ host_network }}'
        start_connected: true
      wait_for_ip_address: yes
    delegate_to: localhost
    register: deploy
